// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: internal/test/proto2_test.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestEnumStruct_TestEnum int32

const (
	TestEnumStruct_unknown TestEnumStruct_TestEnum = 0
	TestEnumStruct_foo     TestEnumStruct_TestEnum = 1
	TestEnumStruct_bar     TestEnumStruct_TestEnum = 2
)

// Enum value maps for TestEnumStruct_TestEnum.
var (
	TestEnumStruct_TestEnum_name = map[int32]string{
		0: "unknown",
		1: "foo",
		2: "bar",
	}
	TestEnumStruct_TestEnum_value = map[string]int32{
		"unknown": 0,
		"foo":     1,
		"bar":     2,
	}
)

func (x TestEnumStruct_TestEnum) Enum() *TestEnumStruct_TestEnum {
	p := new(TestEnumStruct_TestEnum)
	*p = x
	return p
}

func (x TestEnumStruct_TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnumStruct_TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_test_proto2_test_proto_enumTypes[0].Descriptor()
}

func (TestEnumStruct_TestEnum) Type() protoreflect.EnumType {
	return &file_internal_test_proto2_test_proto_enumTypes[0]
}

func (x TestEnumStruct_TestEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TestEnumStruct_TestEnum) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TestEnumStruct_TestEnum(num)
	return nil
}

// Deprecated: Use TestEnumStruct_TestEnum.Descriptor instead.
func (TestEnumStruct_TestEnum) EnumDescriptor() ([]byte, []int) {
	return file_internal_test_proto2_test_proto_rawDescGZIP(), []int{4, 0}
}

type TestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrField   *string          `protobuf:"bytes,1,opt,name=str_field,json=strField" json:"str_field,omitempty"`
	Int32Field *int32           `protobuf:"varint,2,opt,name=int32_field,json=int32Field" json:"int32_field,omitempty"`
	Int64Field *int64           `protobuf:"varint,3,opt,name=int64_field,json=int64Field" json:"int64_field,omitempty"`
	StrList    []string         `protobuf:"bytes,4,rep,name=str_list,json=strList" json:"str_list,omitempty"`
	Metadata   map[string]int64 `protobuf:"bytes,10,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto2_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto2_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_internal_test_proto2_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetStrField() string {
	if x != nil && x.StrField != nil {
		return *x.StrField
	}
	return ""
}

func (x *TestMessage) GetInt32Field() int32 {
	if x != nil && x.Int32Field != nil {
		return *x.Int32Field
	}
	return 0
}

func (x *TestMessage) GetInt64Field() int64 {
	if x != nil && x.Int64Field != nil {
		return *x.Int64Field
	}
	return 0
}

func (x *TestMessage) GetStrList() []string {
	if x != nil {
		return x.StrList
	}
	return nil
}

func (x *TestMessage) GetMetadata() map[string]int64 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TestNestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrField *string `protobuf:"bytes,1,opt,name=str_field,json=strField" json:"str_field,omitempty"`
}

func (x *TestNestedMessage) Reset() {
	*x = TestNestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto2_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestNestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestNestedMessage) ProtoMessage() {}

func (x *TestNestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto2_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestNestedMessage.ProtoReflect.Descriptor instead.
func (*TestNestedMessage) Descriptor() ([]byte, []int) {
	return file_internal_test_proto2_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestNestedMessage) GetStrField() string {
	if x != nil && x.StrField != nil {
		return *x.StrField
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Kind *string `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Op   *string `protobuf:"bytes,3,opt,name=op" json:"op,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto2_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto2_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_internal_test_proto2_test_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Filter) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *Filter) GetOp() string {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return ""
}

type TestGoogleStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StructField *structpb.Struct `protobuf:"bytes,1,opt,name=struct_field,json=structField" json:"struct_field,omitempty"`
}

func (x *TestGoogleStruct) Reset() {
	*x = TestGoogleStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto2_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestGoogleStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestGoogleStruct) ProtoMessage() {}

func (x *TestGoogleStruct) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto2_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestGoogleStruct.ProtoReflect.Descriptor instead.
func (*TestGoogleStruct) Descriptor() ([]byte, []int) {
	return file_internal_test_proto2_test_proto_rawDescGZIP(), []int{3}
}

func (x *TestGoogleStruct) GetStructField() *structpb.Struct {
	if x != nil {
		return x.StructField
	}
	return nil
}

type TestEnumStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnumField *TestEnumStruct_TestEnum `protobuf:"varint,1,opt,name=enum_field,json=enumField,enum=pbts.TestEnumStruct_TestEnum" json:"enum_field,omitempty"`
}

func (x *TestEnumStruct) Reset() {
	*x = TestEnumStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto2_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestEnumStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEnumStruct) ProtoMessage() {}

func (x *TestEnumStruct) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto2_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEnumStruct.ProtoReflect.Descriptor instead.
func (*TestEnumStruct) Descriptor() ([]byte, []int) {
	return file_internal_test_proto2_test_proto_rawDescGZIP(), []int{4}
}

func (x *TestEnumStruct) GetEnumField() TestEnumStruct_TestEnum {
	if x != nil && x.EnumField != nil {
		return *x.EnumField
	}
	return TestEnumStruct_unknown
}

type TestOneofStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Instrument:
	//
	//	*TestOneofStruct_Stock_
	//	*TestOneofStruct_Currency_
	//	*TestOneofStruct_StrField
	Instrument isTestOneofStruct_Instrument `protobuf_oneof:"instrument"`
}

func (x *TestOneofStruct) Reset() {
	*x = TestOneofStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto2_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestOneofStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOneofStruct) ProtoMessage() {}

func (x *TestOneofStruct) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto2_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOneofStruct.ProtoReflect.Descriptor instead.
func (*TestOneofStruct) Descriptor() ([]byte, []int) {
	return file_internal_test_proto2_test_proto_rawDescGZIP(), []int{5}
}

func (m *TestOneofStruct) GetInstrument() isTestOneofStruct_Instrument {
	if m != nil {
		return m.Instrument
	}
	return nil
}

func (x *TestOneofStruct) GetStock() *TestOneofStruct_Stock {
	if x, ok := x.GetInstrument().(*TestOneofStruct_Stock_); ok {
		return x.Stock
	}
	return nil
}

func (x *TestOneofStruct) GetCurrency() *TestOneofStruct_Currency {
	if x, ok := x.GetInstrument().(*TestOneofStruct_Currency_); ok {
		return x.Currency
	}
	return nil
}

func (x *TestOneofStruct) GetStrField() string {
	if x, ok := x.GetInstrument().(*TestOneofStruct_StrField); ok {
		return x.StrField
	}
	return ""
}

type isTestOneofStruct_Instrument interface {
	isTestOneofStruct_Instrument()
}

type TestOneofStruct_Stock_ struct {
	Stock *TestOneofStruct_Stock `protobuf:"bytes,1,opt,name=stock,oneof"`
}

type TestOneofStruct_Currency_ struct {
	Currency *TestOneofStruct_Currency `protobuf:"bytes,2,opt,name=currency,oneof"`
}

type TestOneofStruct_StrField struct {
	StrField string `protobuf:"bytes,3,opt,name=str_field,json=strField,oneof"`
}

func (*TestOneofStruct_Stock_) isTestOneofStruct_Instrument() {}

func (*TestOneofStruct_Currency_) isTestOneofStruct_Instrument() {}

func (*TestOneofStruct_StrField) isTestOneofStruct_Instrument() {}

type TestOneofStruct_Stock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (x *TestOneofStruct_Stock) Reset() {
	*x = TestOneofStruct_Stock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto2_test_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestOneofStruct_Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOneofStruct_Stock) ProtoMessage() {}

func (x *TestOneofStruct_Stock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto2_test_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOneofStruct_Stock.ProtoReflect.Descriptor instead.
func (*TestOneofStruct_Stock) Descriptor() ([]byte, []int) {
	return file_internal_test_proto2_test_proto_rawDescGZIP(), []int{5, 0}
}

func (x *TestOneofStruct_Stock) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type TestOneofStruct_Currency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country   *string `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
	ShortCode *string `protobuf:"bytes,2,opt,name=short_code,json=shortCode" json:"short_code,omitempty"`
}

func (x *TestOneofStruct_Currency) Reset() {
	*x = TestOneofStruct_Currency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto2_test_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestOneofStruct_Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOneofStruct_Currency) ProtoMessage() {}

func (x *TestOneofStruct_Currency) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto2_test_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOneofStruct_Currency.ProtoReflect.Descriptor instead.
func (*TestOneofStruct_Currency) Descriptor() ([]byte, []int) {
	return file_internal_test_proto2_test_proto_rawDescGZIP(), []int{5, 1}
}

func (x *TestOneofStruct_Currency) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *TestOneofStruct_Currency) GetShortCode() string {
	if x != nil && x.ShortCode != nil {
		return *x.ShortCode
	}
	return ""
}

var File_internal_test_proto2_test_proto protoreflect.FileDescriptor

var file_internal_test_proto2_test_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x70, 0x62, 0x74, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x02, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x3b, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x62, 0x74, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x30, 0x0a, 0x11, 0x54, 0x65, 0x73,
	0x74, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x74, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x3c, 0x0a, 0x06, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x4e, 0x0a, 0x10, 0x54, 0x65, 0x73,
	0x74, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x3a, 0x0a,
	0x0c, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x79, 0x0a, 0x0e, 0x54, 0x65, 0x73,
	0x74, 0x45, 0x6e, 0x75, 0x6d, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x3c, 0x0a, 0x0a, 0x65,
	0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1d, 0x2e, 0x70, 0x62, 0x74, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x09,
	0x65, 0x6e, 0x75, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x29, 0x0a, 0x08, 0x54, 0x65, 0x73,
	0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x62,
	0x61, 0x72, 0x10, 0x02, 0x22, 0x93, 0x02, 0x0a, 0x0f, 0x54, 0x65, 0x73, 0x74, 0x4f, 0x6e, 0x65,
	0x6f, 0x66, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x74, 0x73, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x3c, 0x0a,
	0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x70, 0x62, 0x74, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x6f, 0x66,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x48,
	0x00, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1d, 0x0a, 0x09, 0x73,
	0x74, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x08, 0x73, 0x74, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x1b, 0x0a, 0x05, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x43, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x0c, 0x0a, 0x0a,
	0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x63, 0x74, 0x61, 0x76, 0x6f, 0x72,
	0x65, 0x2f, 0x70, 0x62, 0x74, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74,
}

var (
	file_internal_test_proto2_test_proto_rawDescOnce sync.Once
	file_internal_test_proto2_test_proto_rawDescData = file_internal_test_proto2_test_proto_rawDesc
)

func file_internal_test_proto2_test_proto_rawDescGZIP() []byte {
	file_internal_test_proto2_test_proto_rawDescOnce.Do(func() {
		file_internal_test_proto2_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_test_proto2_test_proto_rawDescData)
	})
	return file_internal_test_proto2_test_proto_rawDescData
}

var file_internal_test_proto2_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_test_proto2_test_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_test_proto2_test_proto_goTypes = []interface{}{
	(TestEnumStruct_TestEnum)(0),     // 0: pbts.TestEnumStruct.TestEnum
	(*TestMessage)(nil),              // 1: pbts.TestMessage
	(*TestNestedMessage)(nil),        // 2: pbts.TestNestedMessage
	(*Filter)(nil),                   // 3: pbts.Filter
	(*TestGoogleStruct)(nil),         // 4: pbts.TestGoogleStruct
	(*TestEnumStruct)(nil),           // 5: pbts.TestEnumStruct
	(*TestOneofStruct)(nil),          // 6: pbts.TestOneofStruct
	nil,                              // 7: pbts.TestMessage.MetadataEntry
	(*TestOneofStruct_Stock)(nil),    // 8: pbts.TestOneofStruct.Stock
	(*TestOneofStruct_Currency)(nil), // 9: pbts.TestOneofStruct.Currency
	(*structpb.Struct)(nil),          // 10: google.protobuf.Struct
}
var file_internal_test_proto2_test_proto_depIdxs = []int32{
	7,  // 0: pbts.TestMessage.metadata:type_name -> pbts.TestMessage.MetadataEntry
	10, // 1: pbts.TestGoogleStruct.struct_field:type_name -> google.protobuf.Struct
	0,  // 2: pbts.TestEnumStruct.enum_field:type_name -> pbts.TestEnumStruct.TestEnum
	8,  // 3: pbts.TestOneofStruct.stock:type_name -> pbts.TestOneofStruct.Stock
	9,  // 4: pbts.TestOneofStruct.currency:type_name -> pbts.TestOneofStruct.Currency
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_test_proto2_test_proto_init() }
func file_internal_test_proto2_test_proto_init() {
	if File_internal_test_proto2_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_test_proto2_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto2_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestNestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto2_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto2_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestGoogleStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto2_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestEnumStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto2_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestOneofStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto2_test_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestOneofStruct_Stock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto2_test_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestOneofStruct_Currency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_test_proto2_test_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*TestOneofStruct_Stock_)(nil),
		(*TestOneofStruct_Currency_)(nil),
		(*TestOneofStruct_StrField)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_test_proto2_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_test_proto2_test_proto_goTypes,
		DependencyIndexes: file_internal_test_proto2_test_proto_depIdxs,
		EnumInfos:         file_internal_test_proto2_test_proto_enumTypes,
		MessageInfos:      file_internal_test_proto2_test_proto_msgTypes,
	}.Build()
	File_internal_test_proto2_test_proto = out.File
	file_internal_test_proto2_test_proto_rawDesc = nil
	file_internal_test_proto2_test_proto_goTypes = nil
	file_internal_test_proto2_test_proto_depIdxs = nil
}
