// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: internal/test/proto3_test.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestProto3EnumStruct_TestProto3Enum int32

const (
	TestProto3EnumStruct_unknown TestProto3EnumStruct_TestProto3Enum = 0
	TestProto3EnumStruct_foo     TestProto3EnumStruct_TestProto3Enum = 1
	TestProto3EnumStruct_bar     TestProto3EnumStruct_TestProto3Enum = 2
)

// Enum value maps for TestProto3EnumStruct_TestProto3Enum.
var (
	TestProto3EnumStruct_TestProto3Enum_name = map[int32]string{
		0: "unknown",
		1: "foo",
		2: "bar",
	}
	TestProto3EnumStruct_TestProto3Enum_value = map[string]int32{
		"unknown": 0,
		"foo":     1,
		"bar":     2,
	}
)

func (x TestProto3EnumStruct_TestProto3Enum) Enum() *TestProto3EnumStruct_TestProto3Enum {
	p := new(TestProto3EnumStruct_TestProto3Enum)
	*p = x
	return p
}

func (x TestProto3EnumStruct_TestProto3Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestProto3EnumStruct_TestProto3Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_test_proto3_test_proto_enumTypes[0].Descriptor()
}

func (TestProto3EnumStruct_TestProto3Enum) Type() protoreflect.EnumType {
	return &file_internal_test_proto3_test_proto_enumTypes[0]
}

func (x TestProto3EnumStruct_TestProto3Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestProto3EnumStruct_TestProto3Enum.Descriptor instead.
func (TestProto3EnumStruct_TestProto3Enum) EnumDescriptor() ([]byte, []int) {
	return file_internal_test_proto3_test_proto_rawDescGZIP(), []int{3, 0}
}

type TestProto3Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrField    string           `protobuf:"bytes,1,opt,name=str_field,json=strField,proto3" json:"str_field,omitempty"`
	OptStrField *string          `protobuf:"bytes,2,opt,name=opt_str_field,json=optStrField,proto3,oneof" json:"opt_str_field,omitempty"`
	Int32Field  int32            `protobuf:"varint,3,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field  int64            `protobuf:"varint,4,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	StrList     []string         `protobuf:"bytes,5,rep,name=str_list,json=strList,proto3" json:"str_list,omitempty"`
	Metadata    map[string]int64 `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *TestProto3Message) Reset() {
	*x = TestProto3Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto3_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestProto3Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProto3Message) ProtoMessage() {}

func (x *TestProto3Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto3_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProto3Message.ProtoReflect.Descriptor instead.
func (*TestProto3Message) Descriptor() ([]byte, []int) {
	return file_internal_test_proto3_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestProto3Message) GetStrField() string {
	if x != nil {
		return x.StrField
	}
	return ""
}

func (x *TestProto3Message) GetOptStrField() string {
	if x != nil && x.OptStrField != nil {
		return *x.OptStrField
	}
	return ""
}

func (x *TestProto3Message) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *TestProto3Message) GetInt64Field() int64 {
	if x != nil {
		return x.Int64Field
	}
	return 0
}

func (x *TestProto3Message) GetStrList() []string {
	if x != nil {
		return x.StrList
	}
	return nil
}

func (x *TestProto3Message) GetMetadata() map[string]int64 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TestProto3NestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrField string `protobuf:"bytes,1,opt,name=str_field,json=strField,proto3" json:"str_field,omitempty"`
}

func (x *TestProto3NestedMessage) Reset() {
	*x = TestProto3NestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto3_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestProto3NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProto3NestedMessage) ProtoMessage() {}

func (x *TestProto3NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto3_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProto3NestedMessage.ProtoReflect.Descriptor instead.
func (*TestProto3NestedMessage) Descriptor() ([]byte, []int) {
	return file_internal_test_proto3_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestProto3NestedMessage) GetStrField() string {
	if x != nil {
		return x.StrField
	}
	return ""
}

type TestProto3GoogleStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StructField *structpb.Struct `protobuf:"bytes,1,opt,name=struct_field,json=structField,proto3" json:"struct_field,omitempty"`
}

func (x *TestProto3GoogleStruct) Reset() {
	*x = TestProto3GoogleStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto3_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestProto3GoogleStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProto3GoogleStruct) ProtoMessage() {}

func (x *TestProto3GoogleStruct) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto3_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProto3GoogleStruct.ProtoReflect.Descriptor instead.
func (*TestProto3GoogleStruct) Descriptor() ([]byte, []int) {
	return file_internal_test_proto3_test_proto_rawDescGZIP(), []int{2}
}

func (x *TestProto3GoogleStruct) GetStructField() *structpb.Struct {
	if x != nil {
		return x.StructField
	}
	return nil
}

type TestProto3EnumStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnumField TestProto3EnumStruct_TestProto3Enum `protobuf:"varint,1,opt,name=enum_field,json=enumField,proto3,enum=pbts.TestProto3EnumStruct_TestProto3Enum" json:"enum_field,omitempty"`
}

func (x *TestProto3EnumStruct) Reset() {
	*x = TestProto3EnumStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto3_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestProto3EnumStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProto3EnumStruct) ProtoMessage() {}

func (x *TestProto3EnumStruct) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto3_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProto3EnumStruct.ProtoReflect.Descriptor instead.
func (*TestProto3EnumStruct) Descriptor() ([]byte, []int) {
	return file_internal_test_proto3_test_proto_rawDescGZIP(), []int{3}
}

func (x *TestProto3EnumStruct) GetEnumField() TestProto3EnumStruct_TestProto3Enum {
	if x != nil {
		return x.EnumField
	}
	return TestProto3EnumStruct_unknown
}

type TestProto3OneOfStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Pet:
	//
	//	*TestProto3OneOfStruct_Cat_
	//	*TestProto3OneOfStruct_Dog_
	//	*TestProto3OneOfStruct_Other
	Pet isTestProto3OneOfStruct_Pet `protobuf_oneof:"pet"`
}

func (x *TestProto3OneOfStruct) Reset() {
	*x = TestProto3OneOfStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto3_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestProto3OneOfStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProto3OneOfStruct) ProtoMessage() {}

func (x *TestProto3OneOfStruct) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto3_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProto3OneOfStruct.ProtoReflect.Descriptor instead.
func (*TestProto3OneOfStruct) Descriptor() ([]byte, []int) {
	return file_internal_test_proto3_test_proto_rawDescGZIP(), []int{4}
}

func (m *TestProto3OneOfStruct) GetPet() isTestProto3OneOfStruct_Pet {
	if m != nil {
		return m.Pet
	}
	return nil
}

func (x *TestProto3OneOfStruct) GetCat() *TestProto3OneOfStruct_Cat {
	if x, ok := x.GetPet().(*TestProto3OneOfStruct_Cat_); ok {
		return x.Cat
	}
	return nil
}

func (x *TestProto3OneOfStruct) GetDog() *TestProto3OneOfStruct_Dog {
	if x, ok := x.GetPet().(*TestProto3OneOfStruct_Dog_); ok {
		return x.Dog
	}
	return nil
}

func (x *TestProto3OneOfStruct) GetOther() string {
	if x, ok := x.GetPet().(*TestProto3OneOfStruct_Other); ok {
		return x.Other
	}
	return ""
}

type isTestProto3OneOfStruct_Pet interface {
	isTestProto3OneOfStruct_Pet()
}

type TestProto3OneOfStruct_Cat_ struct {
	Cat *TestProto3OneOfStruct_Cat `protobuf:"bytes,1,opt,name=cat,proto3,oneof"`
}

type TestProto3OneOfStruct_Dog_ struct {
	Dog *TestProto3OneOfStruct_Dog `protobuf:"bytes,2,opt,name=dog,proto3,oneof"`
}

type TestProto3OneOfStruct_Other struct {
	Other string `protobuf:"bytes,3,opt,name=other,proto3,oneof"`
}

func (*TestProto3OneOfStruct_Cat_) isTestProto3OneOfStruct_Pet() {}

func (*TestProto3OneOfStruct_Dog_) isTestProto3OneOfStruct_Pet() {}

func (*TestProto3OneOfStruct_Other) isTestProto3OneOfStruct_Pet() {}

type TestProto3OneOfStruct_Cat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meow string `protobuf:"bytes,1,opt,name=meow,proto3" json:"meow,omitempty"`
}

func (x *TestProto3OneOfStruct_Cat) Reset() {
	*x = TestProto3OneOfStruct_Cat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto3_test_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestProto3OneOfStruct_Cat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProto3OneOfStruct_Cat) ProtoMessage() {}

func (x *TestProto3OneOfStruct_Cat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto3_test_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProto3OneOfStruct_Cat.ProtoReflect.Descriptor instead.
func (*TestProto3OneOfStruct_Cat) Descriptor() ([]byte, []int) {
	return file_internal_test_proto3_test_proto_rawDescGZIP(), []int{4, 0}
}

func (x *TestProto3OneOfStruct_Cat) GetMeow() string {
	if x != nil {
		return x.Meow
	}
	return ""
}

type TestProto3OneOfStruct_Dog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bark string `protobuf:"bytes,1,opt,name=bark,proto3" json:"bark,omitempty"`
}

func (x *TestProto3OneOfStruct_Dog) Reset() {
	*x = TestProto3OneOfStruct_Dog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_test_proto3_test_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestProto3OneOfStruct_Dog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProto3OneOfStruct_Dog) ProtoMessage() {}

func (x *TestProto3OneOfStruct_Dog) ProtoReflect() protoreflect.Message {
	mi := &file_internal_test_proto3_test_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProto3OneOfStruct_Dog.ProtoReflect.Descriptor instead.
func (*TestProto3OneOfStruct_Dog) Descriptor() ([]byte, []int) {
	return file_internal_test_proto3_test_proto_rawDescGZIP(), []int{4, 1}
}

func (x *TestProto3OneOfStruct_Dog) GetBark() string {
	if x != nil {
		return x.Bark
	}
	return ""
}

var File_internal_test_proto3_test_proto protoreflect.FileDescriptor

var file_internal_test_proto3_test_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x70, 0x62, 0x74, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc8, 0x02, 0x0a, 0x11, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x33, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x74, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x74, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x27, 0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x5f,
	0x73, 0x74, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0b, 0x6f, 0x70, 0x74, 0x53, 0x74, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x41,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x70, 0x62, 0x74, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x33, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x10,
	0x0a, 0x0e, 0x5f, 0x6f, 0x70, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x22, 0x36, 0x0a, 0x17, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x4e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x74, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x74, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x54, 0x0a, 0x16, 0x54, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x12, 0x3a, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x91,
	0x01, 0x0a, 0x14, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x45, 0x6e, 0x75,
	0x6d, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x48, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x70, 0x62,
	0x74, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x45, 0x6e, 0x75,
	0x6d, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x33, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x09, 0x65, 0x6e, 0x75, 0x6d, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x22, 0x2f, 0x0a, 0x0e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x45,
	0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x62, 0x61, 0x72,
	0x10, 0x02, 0x22, 0xd6, 0x01, 0x0a, 0x15, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x33, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x33, 0x0a, 0x03,
	0x63, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x62, 0x74, 0x73,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x4f, 0x6e, 0x65, 0x4f, 0x66,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x48, 0x00, 0x52, 0x03, 0x63, 0x61,
	0x74, 0x12, 0x33, 0x0a, 0x03, 0x64, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x70, 0x62, 0x74, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x33,
	0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x44, 0x6f, 0x67, 0x48,
	0x00, 0x52, 0x03, 0x64, 0x6f, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x1a, 0x19,
	0x0a, 0x03, 0x43, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6f, 0x77, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x6f, 0x77, 0x1a, 0x19, 0x0a, 0x03, 0x44, 0x6f, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x61, 0x72, 0x6b, 0x42, 0x05, 0x0a, 0x03, 0x70, 0x65, 0x74, 0x42, 0x28, 0x5a, 0x26, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x63, 0x74, 0x61, 0x76, 0x6f,
	0x72, 0x65, 0x2f, 0x70, 0x62, 0x74, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_test_proto3_test_proto_rawDescOnce sync.Once
	file_internal_test_proto3_test_proto_rawDescData = file_internal_test_proto3_test_proto_rawDesc
)

func file_internal_test_proto3_test_proto_rawDescGZIP() []byte {
	file_internal_test_proto3_test_proto_rawDescOnce.Do(func() {
		file_internal_test_proto3_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_test_proto3_test_proto_rawDescData)
	})
	return file_internal_test_proto3_test_proto_rawDescData
}

var file_internal_test_proto3_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_test_proto3_test_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_test_proto3_test_proto_goTypes = []interface{}{
	(TestProto3EnumStruct_TestProto3Enum)(0), // 0: pbts.TestProto3EnumStruct.TestProto3Enum
	(*TestProto3Message)(nil),                // 1: pbts.TestProto3Message
	(*TestProto3NestedMessage)(nil),          // 2: pbts.TestProto3NestedMessage
	(*TestProto3GoogleStruct)(nil),           // 3: pbts.TestProto3GoogleStruct
	(*TestProto3EnumStruct)(nil),             // 4: pbts.TestProto3EnumStruct
	(*TestProto3OneOfStruct)(nil),            // 5: pbts.TestProto3OneOfStruct
	nil,                                      // 6: pbts.TestProto3Message.MetadataEntry
	(*TestProto3OneOfStruct_Cat)(nil),        // 7: pbts.TestProto3OneOfStruct.Cat
	(*TestProto3OneOfStruct_Dog)(nil),        // 8: pbts.TestProto3OneOfStruct.Dog
	(*structpb.Struct)(nil),                  // 9: google.protobuf.Struct
}
var file_internal_test_proto3_test_proto_depIdxs = []int32{
	6, // 0: pbts.TestProto3Message.metadata:type_name -> pbts.TestProto3Message.MetadataEntry
	9, // 1: pbts.TestProto3GoogleStruct.struct_field:type_name -> google.protobuf.Struct
	0, // 2: pbts.TestProto3EnumStruct.enum_field:type_name -> pbts.TestProto3EnumStruct.TestProto3Enum
	7, // 3: pbts.TestProto3OneOfStruct.cat:type_name -> pbts.TestProto3OneOfStruct.Cat
	8, // 4: pbts.TestProto3OneOfStruct.dog:type_name -> pbts.TestProto3OneOfStruct.Dog
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_test_proto3_test_proto_init() }
func file_internal_test_proto3_test_proto_init() {
	if File_internal_test_proto3_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_test_proto3_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestProto3Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto3_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestProto3NestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto3_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestProto3GoogleStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto3_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestProto3EnumStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto3_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestProto3OneOfStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto3_test_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestProto3OneOfStruct_Cat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_test_proto3_test_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestProto3OneOfStruct_Dog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_test_proto3_test_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_internal_test_proto3_test_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*TestProto3OneOfStruct_Cat_)(nil),
		(*TestProto3OneOfStruct_Dog_)(nil),
		(*TestProto3OneOfStruct_Other)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_test_proto3_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_test_proto3_test_proto_goTypes,
		DependencyIndexes: file_internal_test_proto3_test_proto_depIdxs,
		EnumInfos:         file_internal_test_proto3_test_proto_enumTypes,
		MessageInfos:      file_internal_test_proto3_test_proto_msgTypes,
	}.Build()
	File_internal_test_proto3_test_proto = out.File
	file_internal_test_proto3_test_proto_rawDesc = nil
	file_internal_test_proto3_test_proto_goTypes = nil
	file_internal_test_proto3_test_proto_depIdxs = nil
}
